### ISSUE TITLE
dist naming inconsistancies

### ISSUE THREAD

**Issue by barlock** [IBM-Design/icons#23]
The microphone-recording icon only exists as a png.

**Comment by jhnsnc** [comment]
Here are the discrepancies in file names between the PNG and SVG folders.

| type/folder | PNG name | SVG name | suggested change | use |
| --- | --- | --- | --- | --- |
| action-based | go-forward | forward | go-forward | PNG |
| action-based | revert | reset | reset | SVG |
| action-based | zoomout | zoom-out | zoom-out | SVG |
| formatting | bullet-list_32 | bulleted-list_32 | bulleted-list_32 | SVG |
| formatting | table | tables | table | PNG |
| object-based | applications | application | application | SVG |
| object-based | mobile_64-phone | mobile-phone_64 | mobile-phone_64 | SVG |
| object-based | PDF-file | pdf-file_128 | pdf-file_128 | SVG |
| object-based | PDF-file | pdf-file | pdf-file | SVG |
| object-based | recommended | recommendation | recommendation | SVG |
| object-based | microphone-recording | recording | recording | SVG |
| object-based | videofile | video-file | video-file | SVG |

**Comment by jhnsnc** [comment]
Here are some file names that just strike me as odd. I'm not sure about how to change some of them, but I figured I should point them out. These changes aren't required at all, because the names are consistent between SVG/PNG folders.

| type/folder | name | suggested change |
| --- | --- | --- |
| action-based | add-new | add |
| action-based | down-to-bottom | scroll-to-bottom (?) |
| action-based | overview | ??? don't know |
| action-based | power | ??? don't know |
| action-based | previous | go-back |
| action-based | up-to-top | scroll-to-top |
| object-based | menu-overflow | ??? overflow? |
| object-based | phone-call | phone |
| object-based | wikis | wiki (?) |

Here are the patterns I was using to see if the file names sounded good or not:
- action-based = "You can _________ [this thing]."
- object-based = "This is [a/an] _________." or "These are _________."
- the 'formatting' folder is a bit unique, but I think the names are all pretty good
- I really don't understand the purpose of the 'glyphs' folder

**Comment by slapjack7** [comment]
@hchughes should weigh in on this...the naming has impact on the way the files show on the site, if i'm not mistaken.

**Comment by barlock** [comment]
@slapjack7 all of the file naming conventions will come from the illustrator art boards which @hchughes had a say in. There were problems doing manual exports of all 877 icons (if you can possibly imagine) and they should be fixed and contestant in the 2.0.0 release. I'm working hard to balance getting that release out with the rest of my day job. If you would like to help. I welcome prs! https://github.com/IBM-Design/icons/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0

**Comment by hchughes** [comment]
Hi @mbarlock - the names that are on the site itself are the names of the icons, full stop. The names of the most recent glyphs should match 1-to-1 with the corresponding icons they relate to. http://www.ibm.com/design/language/resources/icon-library

**Comment by hchughes** [comment]
@jhnsnc If these are recommended changes to the names of 9 or so of them, I'm happy to look them over today and get back to you all on those.

**Comment by barlock** [comment]
Gotcha, thats easily not true right now :stuck_out_tongue:. All of the names will be coming from the names of the individual art boards that @poofichu is making ( :heart: ). Before I push `2.0.0` we should make sure that all those are in sync

**Comment by barlock** [comment]
@hchughes from #18 we're changing the way the .ai files are structured so that it doesn't take 3 years to export all the icons. Once we have those updates that is the place we need to evaluate the names

**Comment by jhnsnc** [comment]
Great. And to be clear, the "recommended" column is my personal opinion. I did not reference the IBM Design Language site.

**Comment by kevinSuttle** [comment]
Should be easy to automate, generate, and validate.

**Comment by barlock** [comment]
Already done! I missed closing this. All the icons align with what is in the [icon library](http://www.ibm.com/design/language/resources/icon-library)

**Comment by barlock** [comment]
Fixed by #33

**Comment by kevinSuttle** [comment]
:shipit:
